---
# tasks file for ansible-role-phantomjs

- name: Copy PhantomJS (offline)
  become: yes
  copy: src="files/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2" dest="/tmp" mode=0644
  when: offline_install|bool

- name: Install PhantomJS (offline)
  become: yes
  script: "files/install_phantomjs.sh {{ phantomjs_version }} --offline"
  args:
    creates: /usr/local/share/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs
  when: offline_install|bool

- name: Install PhantomJS (online)
  become: yes
  script: "files/install_phantomjs.sh {{ phantomjs_version }}"
  args:
    creates: /usr/local/share/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs
  when: not offline_install|bool

- name: Check PhantomJS path
  shell: "which phantomjs"
  register: phantomjs_bin
  changed_when: false
  check_mode: no
  tags: debug

- name: Check PhantomJS version
  shell: "phantomjs --version"
  register: phantomjs_result
  changed_when: false
  check_mode: no
  tags: debug

- debug: msg="PhantomJS binary{{':'}} {{ phantomjs_bin.stdout }}"
  tags: debug
- debug: msg="PhantomJS version{{':'}} {{ phantomjs_result.stdout }}"
  tags: debug
